# Generated by Django 4.2.30 on 2026-08-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
